#!/usr/bin/env bash
typedoc --plugin typedoc-plugin-markdown --out docs/ts docs
cat <<- EOF > docs/_interfaces_.md
---
name: Interfaces
route: _interfaces_.md
---
EOF
tail -n +4 docs/ts/modules/_interfaces_.md >> docs/_interfaces_.md
rm -rf docs/ts